trigger:
  branches: 
    include: 
      - main

parameters:
  - name: environment
    displayName: Environment Build In
    type: string
    default: dev
    values: 
      - dev
      - uat
      - prod

variables:
  - name: buildEnv
    value: ${{ parameters.environment }}
  - group: certificateCredential

stages:
############################################################
## Build Stage
############################################################

- stage: Build
  dependsOn: []
  jobs:

############################################################
## installs: npm dependencies 
############################################################
    - job: build_package 
      displayName: SPFx build and packaging
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.13.0' # Specify the Node.js version to use
        - script: npm ci
          displayName: Install npm dependencies 

        - script: |
            echo "Setting BUILD_ENV for environment in: $(buildEnv)"
            export BUILD_ENV=$(buildEnv)
            gulp generate-config 
          displayName: Generate the environment config

############################################################
## updates the configs
############################################################

## installs jq, validates json at every step, integral from ensuring the write config ids are being selected

        - script: |
            echo "Installing jq"
            sudo apt-get update && sudo apt-get install -y jq
          displayName: Install jq

## updates the required libraryId for .yo-rc.json using $CONFIG_FILE

        - script: |
            echo "Use $(buildEnv)"
            CONFIG_FILE="config/env/config.$(buildEnv).json"
            echo "Config file path: $CONFIG_FILE"
          displayName: Identifying config files

        - script: |
            echo "Injecting libraryId from $CONFIG_FILE into .yo-rc.json"
            LIBRARY_ID=$(jq -r '.yoRc.libraryId' $CONFIG_FILE)
            jq --arg libId "$LIBRARY_ID" '.["@microsoft/generator-sharepoint"].libraryId = $libId' .yo-rc.json > temp.json && mv temp.json .yo-rc.json
          displayName: Inject libraryId to .yo-rc.json for Build
        
## updates the required configs (name, id, zippedPackage) for package-solution.json using $CONFIG_FILE

        - script: |
            echo "Reading id, name, zippedPackage from $CONFIG_FILE"
            ID=$(jq -r '.packageSolution.solution.id' $CONFIG_FILE)
            NAME=$(jq -r '.packageSolution.solution.name' $CONFIG_FILE)
            ZIPPED_PACKAGE=$(jq -r '.packageSolution.paths.zippedPackage' $CONFIG_FILE)
            echo "Using Id: $ID"
            echo "Using Name: $NAME"
            echo "Using Zipped Package: $ZIPPED_PACKAGE"
          displayName: Read id, name, zippedPackage from package-solution.json and write to be used config
        
        - script: |
            echo "Injecting id, name, zippedPackage from $CONFIG_FILE into package-solution.json"
            ID=$(jq -r '.packageSolution.solution.id' $CONFIG_FILE)
            jq --arg id "$ID" '.solution.id = $id' config/package-solution.json > temp.json && mv temp.json config/package-solution.json
            NAME=$(jq -r '.packageSolution.solution.name' $CONFIG_FILE)
            jq --arg name "$NAME" '.solution.name = $name' config/package-solution.json > temp.json && mv temp.json config/package-solution.json
            ZIPPED_PACKAGE=$(jq -r '.packageSolution.paths.zippedPackage' $CONFIG_FILE)
            jq --arg zippedPackage "$ZIPPED_PACKAGE" '.paths.zippedPackage = $zippedPackage' config/package-solution.json > temp.json && mv temp.json config/package-solution.json
          displayName: Inject id, name, zippedPackage to package-solution.json for build 

## updates the required configs (groupId, id, title) for .manifest.json using $CONFIG_FILE
        
        - script: |
            echo "Reading id, title, and groupId from webPartManifest"
            MANIFEST_ID=$(jq -r '.webPartManifest.id' $CONFIG_FILE)            
            TITLE=$(jq -r '.webPartManifest.title' $CONFIG_FILE)
            GROUP_ID=$(jq -r '.webPartManifest.groupId' $CONFIG_FILE)
            echo "Using Id: $MANIFEST_ID"
            echo "Using Title: $TITLE"
            echo "Using GroupId: $GROUP_ID"
          displayName: Read id, groupId, and title from .manifest.json and write to be used in config

        - script: |
            echo "Injecting id, title, and groupId from $CONFIG_FILE into .manifest.json"
            MANIFEST_PATH=src/webparts/helloBuildPipeline/HelloBuildPipelineWebPart.manifest.json
            MANIFEST_ID=$(jq -r '.webPartManifest.id' $CONFIG_FILE)
            jq --arg manifestid "$MANIFEST_ID" '.id = $manifestid' "$MANIFEST_PATH" > temp.json && mv temp.json "$MANIFEST_PATH"
            TITLE=$(jq -r '.webPartManifest.title' $CONFIG_FILE)
            jq --argjson title "$TITLE" '.preconfiguredEntries[0].title = $title' "$MANIFEST_PATH" > temp.json && mv temp.json "$MANIFEST_PATH"
            GROUP_ID=$(jq -r '.webPartManifest.groupId' $CONFIG_FILE)
            jq --arg groupid "$GROUP_ID" '.preconfiguredEntries[0].groupId = $groupid' "$MANIFEST_PATH" > temp.json && mv temp.json "$MANIFEST_PATH"
          displayName: Inject id, title, and groupId to .manifest.json for build
          
## dumps the configs being used to verify whether the injection is successful

## < !--- REMOVE FOR DUMP FILE TEST --->

##        - script: |
##            echo "Dumping .yo-rc.json, package-solution.json, and .manifest.js"
##            cat .yo-rc.json
##            cat config/package-solution.json
##            cat src/webparts/helloBuildPipeline/HelloBuildPipelineWebPart.manifest.json
##          displayName: Config dump to verify successful injection

############################################################
## executes: gulp build and cleans
############################################################
        - task: gulp@0
          displayName: SPFx clean
          inputs:
            targets: clean
        - task: gulp@0
          displayName: SPFx build
          inputs:
            targets: build

############################################################
## executes: gulp bundle --ship 
############################################################
        - task: gulp@0
          displayName: SPFx bundle 
          inputs:
            targets: bundle
            arguments: --ship

############################################################
## executes: gulp package-solution --ship
############################################################
        - task: gulp@0
          displayName: SPFx package solution 
          inputs:
            targets: package-solution 
            arguments: --ship

############################################################
## evaluates: the name of the generated *.sppkg package
############################################################
        - script: |
            CMD_GET_SPPKG_NAME=$(find . -name '*.sppkg' -exec basename {} \;)
            echo "##vso[task.setvariable variable=SpPkgFilename;isOutput=true]${CMD_GET_SPPKG_NAME}"
          displayName: Get generated *.sppkg filename 
          name: GetSharePointPackage

############################################################
## copies: *.sppkg as a build artifact 
############################################################
        - task: CopyFiles@2
          inputs:
            sourceFolder: $(Build.Repository.LocalPath)/sharepoint/solution
            contents: '**/*.sppkg'
            targetFolder: $(Build.ArtifactStagingDirectory)  

############################################################
## publishes: *.sppkg as a build artifact 
###########################################################
        - task: PublishBuildArtifacts@1
          displayName: Publish SharePoint Package (*.sppkg)
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)
            artifactName: spfx-package
            publishLocation: 'Container'

- stage: Deployment
  dependsOn:
    - Build
  variables:
    SpPkgFilename: $[StageDependencies.Build.build_package.outputs['GetSharePointPackage.SpPkgFilename']]

############################################################
## Dev Deployment
############################################################

  jobs:
    - deployment: deploy_dev_sppkg
      displayName: Deploy to Dev Environment 
      condition: eq(variables['buildEnv'], 'dev')
      environment: Development 
      strategy: 
        runOnce:
          deploy:
            steps:

############################################################
## installs: Office M365 CLI
############################################################
              - script: sudo npm install --global  @pnp/cli-microsoft365
                displayName: Install OfficeM365 CLI
 
############################################################
## logs in: Office M365 CLI
############################################################
              #- task: AzureCLI@2
                #inputs: 
                  #azureSubscription: sharepoint_integration 
                  #scriptLocation: 'inlineScript'
                  #scriptType: bash
                  #inlineScript: m365 login --authType password --userName "$ServiceAccountEmail" --password "$ServiceAccountPassword" --appId "$App" --tenant "$Tenant"
                #displayName: Login to OfficeM365
                #env:
                  #App: $(AppsID)
                  #Tenant: $(TenantsID)
                  #CertificateID: $(Credential)
                  #PasswordID: $(Password)
                  #ServiceAccountEmail: $(SERVICE_ACCOUNT_EMAIL)
                  #ServiceAccountPassword: $(SERVICE_ACCOUNT_PASSWORD)

############################################################
## logs in: Office M365 CLI
############################################################
              - task: AzureCLI@2
                inputs: 
                  azureSubscription: sharepoint_integration 
                  scriptLocation: 'inlineScript'
                  scriptType: bash
                  inlineScript: m365 login --authType certificate --certificateBase64Encoded "$CertificateID" --appId "$App" --tenant "$Tenant" --password "$PasswordID"
                displayName: Login to OfficeM365
                env:
                  App: $(AppsID)
                  Tenant: $(TenantsID)
                  CertificateID: $(Credential)
                  PasswordID: $(Password)


############################################################
## uploads: the *.sppkg package to the app-catalog
############################################################

              - script: m365 spo app add --debug --verbose -p '$(Pipeline.Workspace)/spfx-package/$(SpPkgFilename)' --appCatalogUrl https://devgcx.sharepoint.com/sites/appcatalog --appCatalogScope tenant --overwrite
                displayName: Upload to SharePoint package to the App Catalog

############################################################
## deploys: the *.sppkg package to the app-catalog
############################################################
              - script:  m365 spo app deploy --debug --verbose --name $(SpPkgFilename) -u https://devgcx.sharepoint.com/sites/appcatalog --appCatalogScope tenant --skipFeatureDeployment
                displayName: Deploy to SharePoint package to the App Catalog

############################################################
## UAT Deployment
############################################################

    - deployment: deploy_uat_sppkg
      displayName: Deploy to UAT Environment 
      condition: eq(variables['buildEnv'], 'uat')
      environment: UAT 
      strategy: 
        runOnce:
          deploy:
            steps:

############################################################
## installs: Office M365 CLI
############################################################
              - script: sudo npm install --global  @pnp/cli-microsoft365
                displayName: Install OfficeM365 CLI
 
############################################################
## logs in: Office M365 CLI
############################################################
              - task: AzureCLI@2
                inputs: 
                  azureSubscription: sharepoint_integration 
                  scriptLocation: 'inlineScript'
                  scriptType: bash
                  inlineScript: m365 login --authType certificate --certificateBase64Encoded "$CertificateID" --appId "$App" --tenant "$Tenant" --password "$PasswordID"
                displayName: Login to OfficeM365
                env:
                  App: $(AppsID)
                  Tenant: $(TenantsID)
                  CertificateID: $(Credential)
                  PasswordID: $(Password)


############################################################
## uploads: the *.sppkg package to the app-catalog
############################################################

              - script: m365 spo app add --debug --verbose -p '$(Pipeline.Workspace)/spfx-package/$(SpPkgFilename)' --appCatalogUrl https://devgcx.sharepoint.com/sites/appcatalog --appCatalogScope tenant --overwrite
                displayName: Upload to SharePoint package to the App Catalog

############################################################
## deploys: the *.sppkg package to the app-catalog
############################################################
              - script:  m365 spo app deploy --debug --verbose --name $(SpPkgFilename) -u https://devgcx.sharepoint.com/sites/appcatalog --appCatalogScope tenant --skipFeatureDeployment
                displayName: Deploy to SharePoint package to the App Catalog

############################################################
## Prod Deployment
############################################################

    - deployment: deploy_prod_sppkg
      displayName: Deploy to Prod Environment 
      condition: eq(variables['buildEnv'], 'prod')
      environment: Production 
      strategy: 
        runOnce:
          deploy:
            steps:

############################################################
## installs: Office M365 CLI
############################################################
              - script: sudo npm install --global  @pnp/cli-microsoft365
                displayName: Install OfficeM365 CLI
 
############################################################
## logs in: Office M365 CLI
############################################################
              - task: AzureCLI@2
                inputs: 
                  azureSubscription: sharepoint_integration 
                  scriptLocation: 'inlineScript'
                  scriptType: bash
                  inlineScript: m365 login --authType certificate --certificateBase64Encoded "$CertificateID" --appId "$App" --tenant "$Tenant" --password "$PasswordID"
                displayName: Login to OfficeM365
                env:
                  App: $(AppsID)
                  Tenant: $(TenantsID)
                  CertificateID: $(Credential)
                  PasswordID: $(Password)


############################################################
## uploads: the *.sppkg package to the app-catalog
############################################################

              - script: m365 spo app add --debug --verbose -p '$(Pipeline.Workspace)/spfx-package/$(SpPkgFilename)' --appCatalogUrl https://devgcx.sharepoint.com/sites/appcatalog --appCatalogScope tenant --overwrite
                displayName: Upload to SharePoint package to the App Catalog

############################################################
## deploys: the *.sppkg package to the app-catalog
############################################################
              - script:  m365 spo app deploy --debug --verbose --name $(SpPkgFilename) -u https://devgcx.sharepoint.com/sites/appcatalog --appCatalogScope tenant --skipFeatureDeployment
                displayName: Deploy to SharePoint package to the App Catalog
